### ISSUE TITLE
Project Info

### ISSUE THREAD

**Issue by DGuidi** [Tummi/SharpMap.Desktop#1]
Only to know: it's this project related to the *official* (although empty) [SharpMap.Desktop](https://github.com/SharpMap/SharpMap.Desktop)?
Looks that this project isn't a fork of the official one, but purposes looks the same, at least looking at the title :)

**Comment by Tummi** [comment]
Yes, but is just an experimental initial commit !
I'll put them there when I have better confidence in github

**Comment by DGuidi** [comment]
So maybe if you create your project as a fork of the official project, this can help you with integration, via github pull requests. My2Cents and have fun with sharpmap :)
